apiVersion: v1
kind: Service
metadata:
  name: {{ include "vmspin.fullname" . }}-lb
  annotations:
    metallb.universe.tf/address-pool: reserved
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
      targetPort: {{ .Values.targetPort }}
  selector:
    kubevirt.io/domain: {{ include "vmspin.fullname" . }}
  type: LoadBalancer
